export interface Listing {
  id: string;
  company: string;
  location: string;
  industry: string;
  subcategory: string;
  type: "offer" | "need";
  title: string;
  capability: string;
  capacity: string;
  leadTime: string;
  moq: string;
  moqLabel?: string;
  availableFrom: string;
  availableUntil: string;
  teamSize: string;
  certifications: string[];
  tags: string[];
  products: string[];
  industriesServed: string[];
  equipment: string;
  equipmentLabel?: string;
  opportunityTags: string[];
  availabilityStatus: "available" | "expiring" | "expired";
  categoryLabel: string;
  posted: string;
  verified: boolean;
  logoColor: string;
  logoLetter: string;
  coverColor: string;
  photoBg: string;
  photoLabel: string;
}

export const mockListings: Listing[] = [
  {
    id: "1",
    company: "Midwest Precision Parts Co.",
    location: "Chicago, IL, USA",
    industry: "Manufacturing",
    subcategory: "CNC Machining",
    type: "offer",
    title: "CNC Machining Capacity Available",
    capability: "CNC Machining, Precision Parts Manufacturing",
    capacity: "500 parts / week",
    leadTime: "3 – 5 days",
    moq: "50 parts",
    availableFrom: "Jun 15, 2026",
    availableUntil: "Dec 15, 2026",
    teamSize: "12",
    certifications: ["ISO 9001:2015", "AS9100D", "ITAR Registered"],
    tags: ["CNC Milling", "CNC Turning", "Precision Parts", "Prototyping", "Tight Tolerances", "Aluminum"],
    products: ["Aluminum Brackets", "Steel Fittings", "Aerospace Components", "Custom Machined Parts"],
    industriesServed: ["Aerospace", "Automotive", "Medical", "Industrial"],
    equipment: "HAAS CNC Mills (3 & 4 Axis) • CNC Lathes • 5-Axis Machining Center",
    equipmentLabel: "Equipment",
    opportunityTags: ["Overflow Production", "Contract Manufacturing", "Prototype Work"],
    availabilityStatus: "available",
    categoryLabel: "Manufacturing",
    posted: "2 days ago",
    verified: true,
    logoColor: "bg-blue-700 text-white",
    logoLetter: "M",
    coverColor: "bg-gradient-to-r from-blue-600 to-blue-800",
    photoBg: "from-slate-600 via-slate-700 to-gray-900",
    photoLabel: "CNC Machining Operations",
  },
  {
    id: "2",
    company: "Summit Cold Storage LLC",
    location: "Denver, CO, USA",
    industry: "Logistics",
    subcategory: "Cold Storage",
    type: "offer",
    title: "Refrigerated Warehousing & Distribution",
    capability: "Refrigerated Warehousing & Distribution",
    capacity: "10,000 pallet positions",
    leadTime: "Same day in / out",
    moq: "-18°C to +4°C",
    moqLabel: "Temperature",
    availableFrom: "Immediately",
    availableUntil: "Ongoing",
    teamSize: "28",
    certifications: ["FDA Registered", "SQF Level 2", "USDA"],
    tags: ["Cold Storage", "Frozen Storage", "Cross Docking", "Distribution"],
    products: ["Frozen Foods", "Dairy Products", "Meat & Poultry", "Pharmaceutical Storage"],
    industriesServed: ["Food Service", "Retail", "E-commerce", "National"],
    equipment: "Blast Freezers • Refrigerated Dock Doors • Temperature Monitoring • Cross-Dock",
    equipmentLabel: "Services",
    opportunityTags: ["Warehousing", "Distribution", "Cold Chain"],
    availabilityStatus: "available",
    categoryLabel: "Logistics",
    posted: "5 days ago",
    verified: true,
    logoColor: "bg-slate-800 text-white",
    logoLetter: "S",
    coverColor: "bg-gradient-to-r from-slate-600 to-slate-800",
    photoBg: "from-slate-400 via-slate-500 to-slate-700",
    photoLabel: "Cold Storage Facility",
  },
  {
    id: "3",
    company: "GreenLeaf Bakery Co.",
    location: "Portland, OR, USA",
    industry: "Food & Beverage",
    subcategory: "Bakery",
    type: "offer",
    title: "Bakery Production Capacity Available",
    capability: "Artisan Baked Goods, Private Label Bakery",
    capacity: "50,000 units / week",
    leadTime: "2 – 4 days",
    moq: "500 units",
    availableFrom: "Immediately",
    availableUntil: "Ongoing",
    teamSize: "35",
    certifications: ["FDA Registered", "SQF", "Organic Certified"],
    tags: ["Bread", "Cookies", "Muffins", "Croissants", "Private Label Baking"],
    products: ["Artisan Bread", "Cookies & Biscuits", "Muffins & Pastries", "Private Label Products"],
    industriesServed: ["Retail", "Food Service", "E-commerce", "Grocery"],
    equipment: "Commercial Ovens • Mixers • Packaging Lines • Gluten-Free Line",
    equipmentLabel: "Equipment",
    opportunityTags: ["Private Label", "Contract Manufacturing", "Overflow Production"],
    availabilityStatus: "available",
    categoryLabel: "Food Production",
    posted: "3 days ago",
    verified: true,
    logoColor: "bg-green-700 text-white",
    logoLetter: "G",
    coverColor: "bg-gradient-to-r from-green-600 to-emerald-700",
    photoBg: "from-amber-300 via-orange-400 to-amber-500",
    photoLabel: "Artisan Bakery",
  },
  {
    id: "4",
    company: "Apex Fabrication Group",
    location: "Detroit, MI, USA",
    industry: "Manufacturing",
    subcategory: "Metal Fabrication",
    type: "offer",
    title: "Metal Fabrication & CNC Services",
    capability: "Sheet Metal Fabrication, Laser Cutting, CNC Machining",
    capacity: "100 tons / month",
    leadTime: "5 – 7 days",
    moq: "100 kg",
    availableFrom: "Jul 1, 2026",
    availableUntil: "Oct 31, 2026",
    teamSize: "18",
    certifications: ["AWS D1.1", "ISO 9001:2015"],
    tags: ["Laser Cutting", "CNC Machining", "Welding", "Sheet Metal", "Powder Coating"],
    products: ["Sheet Metal Parts", "Structural Steel", "Custom Enclosures", "Weldments"],
    industriesServed: ["Automotive", "Industrial", "Construction", "Aerospace"],
    equipment: "Fiber Laser (6kW) • Press Brakes • MIG/TIG Welding • Powder Coating Line",
    equipmentLabel: "Equipment",
    opportunityTags: ["Contract Manufacturing", "Overflow Production"],
    availabilityStatus: "expiring",
    categoryLabel: "Manufacturing",
    posted: "1 week ago",
    verified: true,
    logoColor: "bg-red-700 text-white",
    logoLetter: "A",
    coverColor: "bg-gradient-to-r from-red-500 to-rose-700",
    photoBg: "from-orange-500 via-red-600 to-red-800",
    photoLabel: "Metal Fabrication",
  },
  {
    id: "5",
    company: "PackRite Solutions",
    location: "Chicago, IL, USA",
    industry: "Packaging",
    subcategory: "Custom Packaging",
    type: "offer",
    title: "Custom Packaging Solutions",
    capability: "Custom Corrugated & Retail Packaging Design",
    capacity: "100,000 boxes / day",
    leadTime: "3 – 5 days",
    moq: "500 boxes",
    availableFrom: "Immediately",
    availableUntil: "Ongoing",
    teamSize: "42",
    certifications: ["FSC", "ISO 14001"],
    tags: ["Corrugated Boxes", "Custom Packaging", "Labels", "Retail Packaging"],
    products: ["Corrugated Boxes", "Retail Displays", "Custom Inserts", "Shipping Cartons"],
    industriesServed: ["E-commerce", "Retail", "Food Service", "Industrial"],
    equipment: "Die-Cutters • Flexo Printing • CAD Design • Prototype Shop",
    equipmentLabel: "Equipment",
    opportunityTags: ["Private Label", "Contract Manufacturing"],
    availabilityStatus: "available",
    categoryLabel: "Packaging",
    posted: "4 days ago",
    verified: true,
    logoColor: "bg-amber-500 text-white",
    logoLetter: "P",
    coverColor: "bg-gradient-to-r from-amber-500 to-yellow-600",
    photoBg: "from-amber-300 via-orange-400 to-amber-500",
    photoLabel: "Custom Packaging",
  },
  {
    id: "6",
    company: "BlueLine Transport Inc.",
    location: "Atlanta, GA, USA",
    industry: "Logistics",
    subcategory: "Freight & Transportation",
    type: "offer",
    title: "Flatbed & Dry Van Freight Services",
    capability: "Flatbed & Dry Van Freight, OTR, LTL",
    capacity: "15 trucks available",
    leadTime: "48 hours",
    moq: "Full Truckload",
    moqLabel: "Load Type",
    availableFrom: "Immediately",
    availableUntil: "Ongoing",
    teamSize: "22",
    certifications: ["FMCSA", "DOT", "SmartWay"],
    tags: ["Dry Van", "Flatbed", "OTR Trucking", "LTL", "Expedited Shipping"],
    products: ["Dry Van Freight", "Flatbed Hauling", "LTL Shipments", "Expedited Delivery"],
    industriesServed: ["National", "Regional", "Industrial", "Construction"],
    equipment: "Dry Van Fleet • Flatbed Trailers • GPS Tracking • 24/7 Dispatch",
    equipmentLabel: "Coverage",
    opportunityTags: ["Distribution", "National Coverage"],
    availabilityStatus: "available",
    categoryLabel: "Transportation",
    posted: "3 days ago",
    verified: true,
    logoColor: "bg-blue-700 text-white",
    logoLetter: "B",
    coverColor: "bg-gradient-to-r from-sky-500 to-cyan-600",
    photoBg: "from-sky-400 via-sky-500 to-blue-700",
    photoLabel: "Fleet & Transportation",
  },
  {
    id: "7",
    company: "TechAssembly Solutions",
    location: "Austin, TX, USA",
    industry: "Electronics",
    subcategory: "PCB Assembly",
    type: "offer",
    title: "PCB Assembly & Electronics Manufacturing",
    capability: "PCB Assembly, Electronics Manufacturing, Testing",
    capacity: "1,000 boards / week",
    leadTime: "5 – 7 days",
    moq: "100 boards",
    availableFrom: "Jul 15, 2026",
    availableUntil: "Dec 31, 2026",
    teamSize: "45",
    certifications: ["IPC-A-610", "ISO 9001:2015", "UL Listed"],
    tags: ["PCB Assembly", "SMT", "Box Build", "Testing & Inspection", "NPI"],
    products: ["PCB Assemblies", "Box Builds", "Cable Harnesses", "Test Fixtures"],
    industriesServed: ["Medical", "Industrial", "Automotive", "Electronics"],
    equipment: "SMT Lines • AOI Inspection • X-Ray • Functional Test Stations",
    equipmentLabel: "Equipment",
    opportunityTags: ["Contract Manufacturing", "Prototype Work", "Overflow Production"],
    availabilityStatus: "available",
    categoryLabel: "Electronics",
    posted: "6 days ago",
    verified: true,
    logoColor: "bg-orange-600 text-white",
    logoLetter: "T",
    coverColor: "bg-gradient-to-r from-orange-500 to-amber-600",
    photoBg: "from-orange-400 via-orange-500 to-red-600",
    photoLabel: "PCB Assembly",
  },
  {
    id: "8",
    company: "Coastal Food Co-Pack",
    location: "Seattle, WA, USA",
    industry: "Food & Beverage",
    subcategory: "Co-Packing",
    type: "offer",
    title: "Co-Packing & Food Processing",
    capability: "Co-Packing, Food Processing, Labeling",
    capacity: "20,000 units / day",
    leadTime: "2 weeks",
    moq: "2,000 units",
    availableFrom: "Jun 30, 2026",
    availableUntil: "Ongoing",
    teamSize: "60",
    certifications: ["SQF", "FSSC 22000", "Organic Certified"],
    tags: ["Co-Packing", "Filling & Sealing", "Private Label", "Dry Goods"],
    products: ["Dry Goods", "Snacks", "Beverages", "Private Label Foods"],
    industriesServed: ["Retail", "Food Service", "E-commerce", "Grocery"],
    equipment: "Filling Lines • Sealing Equipment • Labeling • QA Lab",
    equipmentLabel: "Equipment",
    opportunityTags: ["Private Label", "Contract Manufacturing"],
    availabilityStatus: "available",
    categoryLabel: "Food Production",
    posted: "2 days ago",
    verified: true,
    logoColor: "bg-teal-700 text-white",
    logoLetter: "C",
    coverColor: "bg-gradient-to-r from-teal-500 to-cyan-600",
    photoBg: "from-teal-400 via-teal-500 to-teal-700",
    photoLabel: "Food Co-Packing",
  },
  {
    id: "9",
    company: "Northfield Poultry Supply",
    location: "Marshall, MN, USA",
    industry: "Food & Beverage",
    subcategory: "Poultry",
    type: "need",
    title: "Poultry Processing & Packaging Partner Needed",
    capability: "Looking for Poultry Processing & Packaging Partner",
    capacity: "5,000 birds / day",
    leadTime: "1 – 3 days",
    moq: "1,000 birds",
    availableFrom: "Jul 1, 2026",
    availableUntil: "Dec 31, 2026",
    teamSize: "80",
    certifications: ["USDA", "HACCP"],
    tags: ["Chicken", "Turkey", "Poultry Processing", "Packaging", "Distribution"],
    products: ["Whole Chicken", "Turkey Products", "Cut & Pack", "Value-Added Poultry"],
    industriesServed: ["Food Service", "Retail", "Grocery", "National"],
    equipment: "USDA processing line • Vacuum packaging • Blast freezing • Cold storage",
    equipmentLabel: "Requirements",
    opportunityTags: ["Contract Manufacturing", "New Suppliers"],
    availabilityStatus: "available",
    categoryLabel: "Food Production",
    posted: "1 day ago",
    verified: true,
    logoColor: "bg-purple-700 text-white",
    logoLetter: "N",
    coverColor: "bg-gradient-to-r from-purple-600 to-indigo-700",
    photoBg: "",
    photoLabel: "",
  },
  {
    id: "10",
    company: "FreshBake Distribution",
    location: "Dallas, TX, USA",
    industry: "Food & Beverage",
    subcategory: "Bakery",
    type: "need",
    title: "Seeking Refrigerated Trucking Partner",
    capability: "Seeking Refrigerated Trucking Partner",
    capacity: "10 routes / week",
    leadTime: "48 hours",
    moq: "1 truck",
    availableFrom: "Immediately",
    availableUntil: "Ongoing",
    teamSize: "15",
    certifications: ["FDA"],
    tags: ["Refrigerated Trucking", "Cold Chain", "Food Logistics", "Multi-Stop"],
    products: ["Bread & Rolls", "Pastries", "Frozen Bakery", "Multi-temp loads"],
    industriesServed: ["Food Service", "Retail", "Regional", "Grocery"],
    equipment: "Refrigerated trucks • Multi-stop routing • Temperature monitoring",
    equipmentLabel: "Requirements",
    opportunityTags: ["Distribution", "Cold Chain", "New Suppliers"],
    availabilityStatus: "available",
    categoryLabel: "Logistics",
    posted: "3 days ago",
    verified: false,
    logoColor: "bg-lime-700 text-white",
    logoLetter: "F",
    coverColor: "bg-gradient-to-r from-lime-500 to-green-600",
    photoBg: "",
    photoLabel: "",
  },
  {
    id: "11",
    company: "NexGen Devices",
    location: "San Jose, CA, USA",
    industry: "Electronics",
    subcategory: "PCB Assembly",
    type: "need",
    title: "Need PCB Assembly & Testing Capacity",
    capability: "Need PCB Assembly & Testing Capacity",
    capacity: "2,000 boards / week",
    leadTime: "5 days",
    moq: "500 boards",
    availableFrom: "Jul 1, 2026",
    availableUntil: "Oct 1, 2026",
    teamSize: "25",
    certifications: ["IPC-A-610"],
    tags: ["PCB Assembly", "Electronics", "SMT Testing", "NPI", "High Volume"],
    products: ["Medical Device PCBs", "IoT Boards", "Sensor Modules", "Test & Validation"],
    industriesServed: ["Medical", "Electronics", "Industrial", "Automotive"],
    equipment: "SMT capability • AOI • Functional test • IPC-A-610 certified operators",
    equipmentLabel: "Requirements",
    opportunityTags: ["Contract Manufacturing", "New Suppliers"],
    availabilityStatus: "available",
    categoryLabel: "Electronics",
    posted: "2 days ago",
    verified: true,
    logoColor: "bg-cyan-700 text-white",
    logoLetter: "N",
    coverColor: "bg-gradient-to-r from-cyan-500 to-blue-600",
    photoBg: "",
    photoLabel: "",
  },
  {
    id: "12",
    company: "BuildRight Contractors",
    location: "Houston, TX, USA",
    industry: "Construction",
    subcategory: "Concrete",
    type: "need",
    title: "Looking for Concrete Subcontractors",
    capability: "Looking for Concrete Subcontractors",
    capacity: "20,000 sq ft / month",
    leadTime: "1 week",
    moq: "1 project",
    availableFrom: "Jun 15, 2026",
    availableUntil: "Nov 30, 2026",
    teamSize: "50",
    certifications: ["OSHA 30"],
    tags: ["Concrete", "Foundations", "Structural", "Commercial Construction"],
    products: ["Foundations", "Slabs", "Structural Concrete", "Commercial Builds"],
    industriesServed: ["Construction", "Industrial", "Commercial"],
    equipment: "Ready-mix delivery • Pump trucks • Rebar placement • Finishing crews",
    equipmentLabel: "Requirements",
    opportunityTags: ["New Suppliers", "Strategic Partnership"],
    availabilityStatus: "expiring",
    categoryLabel: "Construction",
    posted: "4 days ago",
    verified: false,
    logoColor: "bg-amber-700 text-white",
    logoLetter: "B",
    coverColor: "bg-gradient-to-r from-amber-500 to-yellow-600",
    photoBg: "",
    photoLabel: "",
  },
  {
    id: "13",
    company: "Orion Sportswear",
    location: "Los Angeles, CA, USA",
    industry: "Apparel",
    subcategory: "Cut and Sew",
    type: "need",
    title: "Seeking Cut-and-Sew Contract Manufacturer",
    capability: "Seeking Cut-and-Sew Contract Manufacturer",
    capacity: "5,000 units / month",
    leadTime: "3 weeks",
    moq: "500 units",
    availableFrom: "Aug 1, 2026",
    availableUntil: "Feb 28, 2027",
    teamSize: "8",
    certifications: [],
    tags: ["Apparel", "Cut and Sew", "Athletic Wear", "Private Label"],
    products: ["Athletic Wear", "Team Uniforms", "Activewear", "Private Label Apparel"],
    industriesServed: ["Retail", "Sports", "E-commerce"],
    equipment: "Cut & sew lines • Screen printing • Embroidery • QC inspection",
    equipmentLabel: "Requirements",
    opportunityTags: ["Contract Manufacturing", "Private Label", "New Suppliers"],
    availabilityStatus: "available",
    categoryLabel: "Apparel",
    posted: "5 days ago",
    verified: false,
    logoColor: "bg-pink-700 text-white",
    logoLetter: "O",
    coverColor: "bg-gradient-to-r from-pink-500 to-rose-600",
    photoBg: "",
    photoLabel: "",
  },
  {
    id: "14",
    company: "Hartwell Injection Molding",
    location: "Cincinnati, OH, USA",
    industry: "Plastics",
    subcategory: "Injection Molding",
    type: "offer",
    title: "Injection Molding & Plastic Parts",
    capability: "Injection Molding, Plastic Parts Manufacturing",
    capacity: "300 parts / hour",
    leadTime: "2 – 3 weeks",
    moq: "1,000 parts",
    availableFrom: "Aug 1, 2026",
    availableUntil: "Ongoing",
    teamSize: "20",
    certifications: ["ISO 9001:2015"],
    tags: ["Injection Molding", "Tooling Design", "ABS Parts", "Polypropylene"],
    products: ["ABS Components", "PP Parts", "Custom Tooling", "High-Volume Runs"],
    industriesServed: ["Automotive", "Industrial", "Medical", "Consumer Goods"],
    equipment: "Injection Presses (50–500 ton) • Tool Design • Secondary Ops • QA Lab",
    equipmentLabel: "Equipment",
    opportunityTags: ["Contract Manufacturing", "Overflow Production", "Prototype Work"],
    availabilityStatus: "available",
    categoryLabel: "Manufacturing",
    posted: "1 week ago",
    verified: false,
    logoColor: "bg-yellow-600 text-white",
    logoLetter: "H",
    coverColor: "bg-gradient-to-r from-yellow-500 to-amber-500",
    photoBg: "from-yellow-300 via-yellow-400 to-amber-500",
    photoLabel: "Plastic Molding",
  },
];
